name:                HNumeric
version:             0.2.0.0
github:              "Axect/HNumeric"
license:             BSD3
author:              "Tae Geun Kim"
maintainer:          "edeftg@gmail.com"
copyright:           "2018 Tae Geun Kim"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Haskell Numeric Library with pure functionality & MATLAB Syntax.
category:            Numeric, Linear Algebra, Statistics, Machine Learning

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Axect/HNumeric#readme>

dependencies:
- base >= 4.7 && < 5
- normaldistribution

library:
  source-dirs: src

executables:
  HNumeric-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HNumeric

tests:
  HNumeric-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HNumeric
